services:
  # MongoDB Database Service (using official MongoDB image)
  - type: web
    name: mongo_db
    env: docker
    envVars:
      - key: image
        value: mongo:latest
    plan: free

  # Node.js API Service (from your provided Dockerfile)
  - type: web
    name: node_api
    env: docker
    dockerfilePath: https://github.com/GYaamini/Car_Dealership_fullstack_developer_capstone.git#main:server/database/Dockerfile  # Path to your Node.js Dockerfile
    envVars:
      - key: PORT
        value: 3030
    plan: free

  # Django API Service
  - type: web
    name: django_api
    env: docker
    dockerfilePath: https://github.com/GYaamini/Car_Dealership_fullstack_developer_capstone.git#main:server/Dockerfile  # Correct path to Django's Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: MONGO_URI
        value: "mongodb://mongo_db:27017/db"  # MongoDB URI for Django to connect
    plan: free

  # Sentiment Analysis Microservice
  - type: web
    name: sentianalyser
    env: docker
    dockerfilePath: https://github.com/GYaamini/Car_Dealership_fullstack_developer_capstone.git#main:server/djangoapp/microservices/Dockerfile  # Path to the microservices Dockerfile
    envVars:
      - key: PORT
        value: 5000
    plan: free

  # Frontend Service
  - type: web
    name: web
    env: docker
    dockerfilePath: https://github.com/GYaamini/Car_Dealership_fullstack_developer_capstone.git#main:server/frontend/Dockerfile  # Path to the frontend Dockerfile
    envVars:
      - key: PORT
        value: 3000
    plan: free

volumes:
  mongo_data:
    type: persistent
