version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: 
      context: https://github.com/GYaamini/Car_Dealership_fullstack_developer_capstone.git#main
      dockerfile: server/database/Dockerfile
    image: nodeapp
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db

  # Sentiment Analyzer microservice
  sentianalyser:
    build: 
      context: https://github.com/GYaamini/Car_Dealership_fullstack_developer_capstone.git#main
      dockerfile: server/djangoapp/microservices/Dockerfile
    ports:
      - 5000:5000

  # Frontend
  web:
    build: 
      context: https://github.com/GYaamini/Car_Dealership_fullstack_developer_capstone.git#main
      dockerfile: server/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
     - .:/app/frontend
     - ./node_modules:/app/frontend/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm start
volumes:
  mongo_data: {}
