name: Docker Image SentimentAnalyzer
on:
  push:
    paths:
      - 'server/djangoapp/microservices/**'
  pull_request:
    paths:
      - 'server/djangoapp/microservices/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN

    - name: Build the Docker image
      run: docker build . --file ./server/djangoapp/microservices/Dockerfile --tag gowriyaamini/senti_analyzer:${{ github.sha }}
    - name: Docker push
      run: docker push gowriyaamini/senti_analyzer:${{ github.sha }}